mutation reservaAdd($id: ID, $input: ReservaInput!) {
  reservaAdd(id: $id, input: $input) {
    id
    pago
    dias
    amount
    articulo {
      id
      categoria {
        id
        slug
        nombre
        tipo {
          id
          slug
          nombre
        }
        balneario {
          id
          slug
          nombre
          ciudad {
            _id
            nombre
          }
        }
      }
    }
  }
}
