query categoriaListFront($tipo: String, $balneario: String) {
  categoriaListFront(tipo: $tipo, balneario: $balneario) {
    id
    slug
    nombre
    descripcion
    balneario {
      slug
      nombre
    }
    tipo {
      slug
      nombre
    }
  }
}
