service: default
runtime: nodejs
entrypoint: npm run prod

env: flex
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 6

# network:
#   forwarded_ports:
#     - 8080/tcp

# env_variables:
#   NODE_ENV: 'production'
