# entorno flex, prod
# service: default
# runtime: nodejs
# entrypoint: npm run prod
#
# env: flex
# automatic_scaling:
#   min_num_instances: 1
#   max_num_instances: 6

# entorno standard, dev
service: front
entrypoint: npm run prod
automatic_scaling:
  max_instances: 1

runtime: nodejs14
env_variables:
  MICRO: "https://devmicro-dot-alamar-308401.uc.r.appspot.com"

