entorno flex, prod
service: default
runtime: nodejs
entrypoint: npm run prod

env: flex
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2 

env_variables:
  MICRO: "https://micro-dot-alamar-298818.uc.r.appspot.com"
  LOGIN_URL: "https://alamar.ar"

# entorno standard, dev
# service: default
# entrypoint: npm run prod
# automatic_scaling:
#   max_instances: 1
#
# runtime: nodejs14
# env_variables:
#   MICRO: "https://micro-dot-alamar-308401.uc.r.appspot.com"
#   LOGIN_URL: "https://alamar-308401.uc.r.appspot.com"

