query calificacionGetFront($token: ID!) {
  calificacionGetFront(token: $token) {
    id
    pago
    dias
    amount
    balneario {
      id
      slug
      nombre
      ciudad {
        id
        nombre
      }
    }
    tipo {
      id
      slug
      nombre
    }
  }
}
