query codigoGetIDFront($id: ID) {
  codigoGetIDFront(id: $id) {
    _id
    nombre
    descripcion
    imagen
    images {
      url
      titulo
    }
    expira
    participantes
    success
    cantidad
    actual
    expiro
    imagenCodigo
    codigoLength
    tiempo
  }
}
