query balnearioGetFront($id: ID!) {
  balnearioGetFront(id: $id) {
    _id
    nombre
    descripcion
    checkIn
    checkOut
    imagenes {
      url
      titulo
    }
    planos {
      url
      titulo
    }
    ciudad {
      _id
      nombre
    }
  }
}

