query balnearioListSearch($ciudad: String) {
  balnearioListSearch(ciudad: $ciudad) {
    _id
    nombre
    descripcion
    imagenes {
      url
      titulo
    }
    ciudad {
      _id
      nombre
    }
  }
}

