query balnearioListSearch($ciudad: String, $desde: String, $hasta: String) {
  balnearioListSearch(ciudad: $ciudad, desde: $desde, hasta: $hasta) {
    slug
    nombre
    ciudad
    ciudadSlug
    categoria
    tipo
    tipoSlug
    articulo
    oldPrecio
    precio
    tagNombre
    tagTexto
    tagClase
    tagImagen
    imagen
  }
}
