query balnearioListFrontUltimos {
  balnearioListFrontUltimos {
    _id
    nombre
    direccion
    descripcion
    checkIn
    checkOut
    imagenes {
      url
      titulo
    }
    planos {
      url
      titulo
    }
    ciudad {
      _id
      nombre
    }
  }
}
