query balnearioListFront {
  balnearioListFront {
    id
    slug
    nombre
    direccion
    descripcion
    checkIn
    checkOut
    imagenes {
      url
      title
    }
    planos {
      url
      title
    }
    ciudad {
      id
      slug
      nombre
    }
  }
}
