query precioGetFront($balneario: String, $categoria: String, $desde: String, $hasta: String) {
  precioGetFront(balneario: $balneario, categoria: $categoria, desde: $desde, hasta: $hasta) {
    id
    balneario
    balnearioSlug
    direccion
    ciudad
    ciudadSlug
    categoria
    categoriaSlug
    tipo
    tipoSlug
    articulo
    oldPrecio
    precio
    tagNombre
    tagTexto
    tagClase
    tagImagen
    imagen
    dias
    stock
  }
}
