query precioGetFront($balneario: String, $tipo: String, $numero: Int $desde: String, $hasta: String) {
  precioGetFront(balneario: $balneario, tipo: $tipo, numero: $numero, desde: $desde, hasta: $hasta) {
    id
    balneario
    balnearioSlug
    keyPublic
    direccion
    ciudad
    ciudadSlug
    categoria
    categoriaSlug
    tipo
    tipoSlug
    articulo
    calificacion
    oldPrecio
    precio
    tagNombre
    tagTexto
    tagClase
    tagImagen
    imagen
    dias
    stock
  }
}
